# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: HdivCheckTask@1
  inputs:
    taskProfile: 'Local'
    logPath: '/home/vsts/work/1/s/hdivAgentLog.hlg'
    application: 'spring-petclinic'